apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets-from-vault
  namespace: tv-dashboard-dev
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        tmdb-api-key: "{{ .tmdb_api_key }}"
  data:
  - secretKey: tmdb_api_key
    remoteRef:
      key: dev/api
      property: tmdb_api_key
