services:
  backend:
    env_file: []  # Disable .env file for CI
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TMDB_API_KEY=${TMDB_API_KEY}
  
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend_test:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db_test:5432/tvshows_test
      - TMDB_API_KEY=${TMDB_API_KEY}

  lint:
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}

  frontend:
    environment:
      - VITE_API_URL=http://localhost:4000/api
