apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tv-dashboard-backend:latest # Change if pushing to a remote registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: PGHOST
          value: "postgres"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres"
        - name: PGDATABASE
          value: "tvshows"
        - name: PGPORT
          value: "5432"
        # Add any other environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
