apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-secret-store.yaml

labels:
- pairs:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: tv-dashboard
    app.kubernetes.io/component: security
