apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: PORT
          value: "4000"
        - name: PGHOST
          value: "postgres"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret-vault
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-vault
              key: password
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret-vault
              key: database
        - name: PGPORT
          value: "5432"
        - name: TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets-vault
              key: TMDB_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"