apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        kubernetes:
          serviceAccountRef:
            name: "prod-external-secrets-sa"
