apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret-from-vault
  namespace: tv-dashboard-prod
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret-vault
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .postgres_user }}"
        password: "{{ .postgres_password }}"
        database: "{{ .postgres_db }}"
  data:
  - secretKey: postgres_user
    remoteRef:
      key: prod/database
      property: postgres_user
  - secretKey: postgres_password
    remoteRef:
      key: prod/database
      property: postgres_password
  - secretKey: postgres_db
    remoteRef:
      key: prod/database
      property: postgres_db