apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tv-dashboard-prod

resources:
  - ../../base
  - external-secret-database.yaml
  - external-secret-api.yaml

namePrefix: prod-

labels:
  - pairs:
      environment: prod
      cluster: microk8s

patches:
  - path: postgres-homelab-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-homelab-patch.yaml

images:
  - name: tv-dashboard-backend
    newName: ghcr.io/navillasa/tv-dashboard-k8s/backend
    newTag: v20251015-de14e14
  - name: tv-dashboard-frontend
    newName: ghcr.io/navillasa/tv-dashboard-k8s/frontend
    newTag: v20251015-de14e14