apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tv-dashboard

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-storage.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-alias-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - managed-certificate.yaml

commonLabels:
  app.kubernetes.io/name: tv-dashboard
  app.kubernetes.io/version: "1.0.0"

images:
  - name: tv-dashboard-backend
    newName: gcr.io/tv-dashboard-k8s/tv-dashboard-backend
    newTag: latest
  - name: tv-dashboard-frontend
    newName: gcr.io/tv-dashboard-k8s/tv-dashboard-frontend
    newTag: latest
