apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- prometheus-config.yaml
- prometheus.yaml
- grafana-datasources.yaml
- grafana-dashboard-config.yaml
- grafana-dashboards.yaml
- grafana.yaml
- monitoring-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: tv-dashboard
  app.kubernetes.io/component: monitoring
