name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build lint image
        run: docker compose build lint

      - name: Run lint
        run: docker compose run --rm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests using Docker Compose
        run: docker compose up --build --abort-on-container-exit backend_test

      - name: Show backend_test logs if it fails
        if: failure()
        run: docker compose logs backend_test

  test-frontend:
    runs-on: ubuntu-latest
    services:
      frontend:
        image: tv-dashboard-k8s-frontend
        ports:
          - 3000:80
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Healthcheck frontend
        run: ./frontend/healthcheck.sh http://localhost:3000
